
services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    ports:
      - "9020:5432" #op
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rootusers
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: prisoners

  crudservice:
    image: crudservice:latest
    build: 
      context: ./crud
      dockerfile: Dockerfile
    restart: always
    container_name: crudservice
    ports:
     - "8000:8000" #op
    depends_on:
      - db

  reportservice:
    image: reportservice:latest
    build: 
      context: ./reportservice
      dockerfile: Dockerfile
    restart: always
    container_name: reportservice
    ports:
      - "3001:8000" #op
    depends_on:
      - crudservice

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # Порт для S3 API
      - "9001:9001"  # Порт для MinIO Console (веб-интерфейс)
    environment:
      MINIO_ROOT_USER: minioadmin       # Логин для доступа к MinIO
      MINIO_ROOT_PASSWORD: minioadmin  # Пароль для доступа к MinIO
    volumes:
      - ./minio:/data                    # Монтирование локальной директории для хранения данных
    command: server /data --console-address ":9001"
    restart: always

  locust:
    image: locustmy:latest
    build:
      context: ./locust
      dockerfile: Dockerfile
    container_name: locust
    ports:
      - "8089:8089"  # Веб-интерфейс Locust
    environment:
      LOCUST_HOST: http://crudservice:8000  # URL вашего API внутри Docker сети
    depends_on:
      - crudservice